---
- name: Raspberry version
  hosts: all
#  connection: local
  become: yes
  become_user: root
  tasks:
  - name: Log on which Linux distro is going to be maintained
    debug:
      msg: "The distro is: {{ ansible_distribution|lower }} and the version name is: {{ ansible_distribution_release }}"
